name = "backend"
compatibility_date = "2023-12-01"

# [vars]

# DATABASE_URL="postgres://postgres.dxaefhdwyabbdlqpgvjv:vanshopvansh@aws-0-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"